[package]
name = "remote_io"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.1"
axum = { version = "0.8.1", features = ["http2", "macros", "multipart", "ws"] } 
hyper = { version = "1.6.0", features = ["server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
tower-service = "0.3.3"
