[package]
name = "remote_io"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["http2", "macros", "multipart", "ws"] } 
clap = { version = "4.5.48", features = ["derive"] }
procfs = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
